---
- name: ftp-nfs-refresh
  hosts: ftp-master
  tasks:

  - name: refreshing svc
    shell: |
       bash /root/git/scripts/shell/ftp_refresh.sh
- name: mount -a
  hosts: all
  tasks:

  - name: mount nfs
    shell: |
       sudo mount -a
