---
- name: SALT-CALL STATE.HIGHSTATE
  hosts: all
  tasks: 
  
  - name: To run salt on all hosts
    shell: |
      cd 
      mkdir git
      cd git
      git clone https://github.com/DivakarK22/scripts.git
      bash $HOME/git/scripts/local/gitpull-all.sh #test
      