---
- name: Install Grafana, Prometheus, and Loki
  hosts: all
  become: true
  tasks:
    - name: Install Grafana package
      ansible.builtin.yum:
        name: grafana
        state: present

    - name: Install Prometheus package
      ansible.builtin.yum:
        name: prometheus
        state: present

    - name: Install Loki package
      ansible.builtin.yum:
        name: loki
        state: present