pipeline {
    agent any
    stages {
        stage('Checkout and Pull') {
            steps {
                dir('$HOME/ansible-playbooks') {
                    git branch: 'main', url: 'https://github.com/DivakarK22/ansible-playbooks.git'
                }
            }
        }
        stage('Tasks') {
            steps {
                sh 'ansible-playbooks $HOME/ansible-playbooks/test.yml  || true'
            }
        }          
    }
}