pipeline {
    agent {
        label 'alma-ansible'
    }
    stages {
        stage('Checkout and Pull') {
            steps {
                dir('$WORKSPACE/ansible-playbooks') {
                    git branch: 'main', url: 'https://github.com/DivakarK22/ansible-playbooks.git'
                }
            }
        }
        stage('Updating Inventory file') {
            steps {
                sh 'rm -rf /etc/ansible/hosts || true'
                sh 'cat <<EOF >/etc/ansible/hosts
                    $ip
                    EOF '
            }
        }
        stage('Tasks') {
            steps {
                sh 'ansible-playbook $WORKSPACE/jenkins-playbooks/test.yml  || true'
            }
        }          
    }
}