---
- name: pxe-hooks
  hosts: pxe
  tasks:

  - name: pxe-hooks-update-ks-and-pxe-cfgs
    shell: |
       cd /root/git/pxe-boot/ 
       sudo git pull
       rm -rf /var/lib/tftpboot/pxelinux.cfg/*
       cp /root/git/pxe-boot/pxelinux.cfg/ /var/lib/tftpboot/pxelinux.cfg/
       sudo systemctl restart {xinetd,tftp,vsftpd}
- name: pxe-hooks-ks
  hosts: pxe
  tasks:

  - name: pxe-hooks-update-ks-and-pxe-cfgs
    shell: |
       cd /home/vagrant/git/pxe-boot/
       sudo git pull
       rm -rf /var/www/html/ks.*
       cp /home/vagrant/git/pxe-boot/ks/* /var/www/html/
       sudo systemctl restart httpd
